export const TRACKING_PARAM_PATTERNS = [
  "utm_*",
  "utm_source",
  "utm_medium",
  "utm_campaign",
  "utm_term",
  "utm_content",
  "utm_id",
  "fbclid",
  "gclid",
  "dclid",
  "msclkid",
  "mc_cid",
  "mc_eid",
  "igshid",
  "ref",
  "ref_src",
  "spm",
  "vero_id",
  "_hsenc",
  "_hsmi",
  "pk_campaign",
  "pk_kwd",
  "twclid",
  "mtm_*",
  "ga_*",
  "_ga",
  "_gl",
  "yclid",
  "_openstat",
  "mkt_tok",
  "srsltid",
  "cmpid",
  "os_ehash",
  "__twitter_impression",
  "wt_mc",
  "wtrid",
  "tracking_source",
  "__hsfp",
  "__hssc",
  "__hstc",
  "__s",
  "hsCtaTracking",
  "ml_subscriber",
  "ml_subscriber_hash",
  "oly_anon_id",
  "oly_enc_id",
  "rb_clickid",
  "s_cid",
  "wickedid"
];

export const DEFAULT_SETTINGS = {
  globalEnabled: true,
  defaultMode: "clean",
  redirectUnwrappingEnabled: true,
  allowlist: [],
  blocklist: [],
  sitePolicies: {
    "google.com": {
      mode: "clean",
      compatibilityParams: ["udm=50"]
    }
  }
};
